AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Serverless Application Model example

Globals:
  Api:
    EndpointConfiguration: REGIONAL
    Name: "RasoolAPI"
  Function:
    Timeout: 20
Parameters:
  Environment:
    Type: String
    Default: DEV
    Description: Environment Name
  StandardQueueName:
    Type: String
    Default: DefaultQueueName
    Description: Standard Queue Name
  PersonTableName:
    Type: String
    Default: PersonTable
    Description: Person Table Name

Resources:
  PersonTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: personId
          AttributeType: S
      KeySchema:
        - AttributeName: personId
          KeyType: HASH
      TableName: !Ref PersonTableName
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  PersonDynamoDBStreamHandler:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.example.handler.person.PersonDynamoDBStreamHandler::handleRequest
      Runtime: java8
      MemorySize: 512
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PersonTable
      Environment:
        Variables:
          TABLE_NAME: !Ref PersonTable
      Architectures:
        - x86_64
      CodeUri:
      Events:
        MyDynamoDBStream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt PersonTable.StreamArn
            BatchSize: 10
            StartingPosition: TRIM_HORIZON


  StorePersonFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.example.handler.person.CreatePersonHandler::handleRequest
      Runtime: java8
      MemorySize: 512
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PersonTable
      Environment:
        Variables:
          TABLE_NAME: !Ref PersonTable
      Architectures:
        - x86_64
      CodeUri:
      Events:
        StoreApi:
          Type: Api
          Properties:
            Path: /persons
            Method: POST

  UpdatePersonFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.example.handler.person.UpdatePersonHandler::handleRequest
      Runtime: java8
      MemorySize: 512
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PersonTable
      Environment:
        Variables:
          TABLE_NAME: !Ref PersonTable
      Architectures:
        - x86_64
      CodeUri:
      Events:
        StoreApi:
          Type: Api
          Properties:
            Path: /persons
            Method: PUT

  DeletePersonFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.example.handler.person.DeletePersonHandler::handleRequest
      Runtime: java8
      MemorySize: 512
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PersonTable
      Environment:
        Variables:
          TABLE_NAME: !Ref PersonTable
      Architectures:
        - x86_64
      CodeUri:
      Events:
        StoreApi:
          Type: Api
          Properties:
            Path: /persons
            Method: DELETE

  GetPersonByHTTPParamFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.example.handler.person.PersonHandler::handleGetRequest
      Runtime: java8
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref PersonTable
      Environment:
        Variables:
          TABLE_NAME: !Ref PersonTable
      MemorySize: 512
      Architectures:
        - x86_64
      CodeUri:
      Events:
        GetPerson:
          Type: Api
          Properties:
            Path: /persons/{id}
            Method: GET
  #        GetAllPerson:
  #          Type: Api
  #          Properties:
  #            Path: /persons
  #            Method: GET

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.example.handler.App::handleRequest
      Runtime: java8
      MemorySize: 512
      Architectures:
        - x86_64
      CodeUri:
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /test
            Method: GET

  MyQueueHandler:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.example.handler.MyQueueRequestHandler::handleRequest
      Runtime: java8
      MemorySize: 512
      Tracing: Active
      Architectures:
        - x86_64
      CodeUri:
      Events:
        HelloWorld:
          Type: SQS
          Properties:
            Queue: !GetAtt MyQueue.Arn
            BatchSize: 1

  MyQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref StandardQueueName


Outputs:
  StandardQueueURL:
    Description: Queue URL for standard queue
    Value: !Ref MyQueue
  StandardQueueArn:
    Description: Queue Arn for Standard queue
    Value: !GetAtt MyQueue.Arn